# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: digitalio-service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'digitalio-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64igitalio-service.proto\x12\rhal.digitalio\x1a\x1bgoogle/protobuf/empty.proto\"l\n\x08IODevice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.hal.digitalio.IOType\x12-\n\tdirection\x18\x03 \x01(\x0e\x32\x1a.hal.digitalio.IODirection\"G\n\x1b\x44igitalIOListDeviceResponse\x12(\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x17.hal.digitalio.IODevice\"[\n\x1c\x44igitalIOSetDirectionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12-\n\tdirection\x18\x02 \x01(\x0e\x32\x1a.hal.digitalio.IODirection\"$\n\x14\x44igitalIOReadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\">\n\x15\x44igitalIOReadResponse\x12%\n\x05state\x18\x01 \x01(\x0e\x32\x16.hal.digitalio.IOState\"L\n\x15\x44igitalIOWriteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x05state\x18\x02 \x01(\x0e\x32\x16.hal.digitalio.IOState\"p\n\x17\x44igitalIOAttachResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x05state\x18\x02 \x01(\x0e\x32\x16.hal.digitalio.IOState\x12\r\n\x05\x65rror\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\t*2\n\x06IOType\x12\t\n\x05INPUT\x10\x00\x12\n\n\x06OUTPUT\x10\x01\x12\x11\n\rBIDIRECTIONAL\x10\x02*\x1e\n\x0bIODirection\x12\x06\n\x02IN\x10\x00\x12\x07\n\x03OUT\x10\x01*\'\n\x07IOState\x12\t\n\x05\x45RROR\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\x08\n\x04HIGH\x10\x02\x32\xa3\x03\n\tDigitalIO\x12S\n\x0bListDevices\x12\x16.google.protobuf.Empty\x1a*.hal.digitalio.DigitalIOListDeviceResponse\"\x00\x12U\n\x0cSetDirection\x12+.hal.digitalio.DigitalIOSetDirectionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12S\n\x04Read\x12#.hal.digitalio.DigitalIOReadRequest\x1a$.hal.digitalio.DigitalIOReadResponse\"\x00\x12G\n\x05Write\x12$.hal.digitalio.DigitalIOWriteRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n\x06\x41ttach\x12\x16.google.protobuf.Empty\x1a&.hal.digitalio.DigitalIOAttachResponse\"\x00\x30\x01\x42\x11Z\x0f./protos;protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digitalio_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./protos;protos'
  _globals['_IOTYPE']._serialized_start=641
  _globals['_IOTYPE']._serialized_end=691
  _globals['_IODIRECTION']._serialized_start=693
  _globals['_IODIRECTION']._serialized_end=723
  _globals['_IOSTATE']._serialized_start=725
  _globals['_IOSTATE']._serialized_end=764
  _globals['_IODEVICE']._serialized_start=71
  _globals['_IODEVICE']._serialized_end=179
  _globals['_DIGITALIOLISTDEVICERESPONSE']._serialized_start=181
  _globals['_DIGITALIOLISTDEVICERESPONSE']._serialized_end=252
  _globals['_DIGITALIOSETDIRECTIONREQUEST']._serialized_start=254
  _globals['_DIGITALIOSETDIRECTIONREQUEST']._serialized_end=345
  _globals['_DIGITALIOREADREQUEST']._serialized_start=347
  _globals['_DIGITALIOREADREQUEST']._serialized_end=383
  _globals['_DIGITALIOREADRESPONSE']._serialized_start=385
  _globals['_DIGITALIOREADRESPONSE']._serialized_end=447
  _globals['_DIGITALIOWRITEREQUEST']._serialized_start=449
  _globals['_DIGITALIOWRITEREQUEST']._serialized_end=525
  _globals['_DIGITALIOATTACHRESPONSE']._serialized_start=527
  _globals['_DIGITALIOATTACHRESPONSE']._serialized_end=639
  _globals['_DIGITALIO']._serialized_start=767
  _globals['_DIGITALIO']._serialized_end=1186
# @@protoc_insertion_point(module_scope)
