# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import digitalio_service_pb2 as digitalio__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in digitalio_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DigitalIOStub(object):
    """*
    Service exposing DigitalIO functions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/hal.digitalio.DigitalIO/ListDevices',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=digitalio__service__pb2.DigitalIOListDeviceResponse.FromString,
                _registered_method=True)
        self.SetDirection = channel.unary_unary(
                '/hal.digitalio.DigitalIO/SetDirection',
                request_serializer=digitalio__service__pb2.DigitalIOSetDirectionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/hal.digitalio.DigitalIO/Read',
                request_serializer=digitalio__service__pb2.DigitalIOReadRequest.SerializeToString,
                response_deserializer=digitalio__service__pb2.DigitalIOReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/hal.digitalio.DigitalIO/Write',
                request_serializer=digitalio__service__pb2.DigitalIOWriteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Attach = channel.unary_stream(
                '/hal.digitalio.DigitalIO/Attach',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=digitalio__service__pb2.DigitalIOAttachResponse.FromString,
                _registered_method=True)


class DigitalIOServicer(object):
    """*
    Service exposing DigitalIO functions.
    """

    def ListDevices(self, request, context):
        """/ Used to retrieve all available digital IO devices.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDirection(self, request, context):
        """/ Used to set pin direction value of a particular gpio pin.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """/ Used to read value of a particular gpio pin.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """/ Used to write value of a particular gpio pin.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attach(self, request, context):
        """/ Used to stream input events form device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DigitalIOServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=digitalio__service__pb2.DigitalIOListDeviceResponse.SerializeToString,
            ),
            'SetDirection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDirection,
                    request_deserializer=digitalio__service__pb2.DigitalIOSetDirectionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=digitalio__service__pb2.DigitalIOReadRequest.FromString,
                    response_serializer=digitalio__service__pb2.DigitalIOReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=digitalio__service__pb2.DigitalIOWriteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Attach': grpc.unary_stream_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=digitalio__service__pb2.DigitalIOAttachResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hal.digitalio.DigitalIO', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hal.digitalio.DigitalIO', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DigitalIO(object):
    """*
    Service exposing DigitalIO functions.
    """

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.digitalio.DigitalIO/ListDevices',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            digitalio__service__pb2.DigitalIOListDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDirection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.digitalio.DigitalIO/SetDirection',
            digitalio__service__pb2.DigitalIOSetDirectionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.digitalio.DigitalIO/Read',
            digitalio__service__pb2.DigitalIOReadRequest.SerializeToString,
            digitalio__service__pb2.DigitalIOReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.digitalio.DigitalIO/Write',
            digitalio__service__pb2.DigitalIOWriteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hal.digitalio.DigitalIO/Attach',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            digitalio__service__pb2.DigitalIOAttachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
